steps:
  # Step 1: Masuk ke folder root monorepo (tiket-wisata-desa)
  - name: "node:22"
    dir: "tiket-wisata-desa"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g pnpm
        
        # Buat file .env di dalam folder aplikasi
        echo "VITE_API_URL=${_VITE_API_URL}" > apps/user-web/.env.production

        # Jalankan install di root monorepo yang sebenarnya
        pnpm install

        # Jalankan build khusus untuk user-web
        pnpm --filter user-web build

  # Step 2: Deploy ke App Engine (jalur disesuaikan dengan sub-folder)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "tiket-wisata-desa/apps/user-web"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy app.yaml --quiet

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY